name: Python Test

on:
  push:
    branches:
      - '**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
        
      - name: Run greet script
        run: |
          cd hw1
          ./complement.py --seq ATTCATGAGTTAAATGGCATCTTAATGTTG
          ./count_kmers.py --fa test.fa -k 4 --out out.json